env                      = "spoke-dev"
aks_location             = "North Europe"
spoke_vnet_address_space = "10.0.0.0/16"
mgm_rg_name              = "management"
mgm_vnet_name            = "management-vnet"