name: Deploy App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_USE_MSI: "true"
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  codeql-scan:
    name: CodeQL Scan
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: navonron/nextjsbasicapp
          token: ${{ secrets.CHART_REPO_TOKEN }}
          path: nextjsbasicapp

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          fail-on-error: true

  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: codeql-scan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: navonron/nextjsbasicapp
          token: ${{ secrets.CHART_REPO_TOKEN }}
          path: nextjsbasicapp

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        working-directory: ./nextjsbasicapp
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest .

      - name: Push Docker Image to Docker Hub
        working-directory: ./nextjsbasicapp
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Deploy to AKS
        working-directory: ./nextjsbasicapp
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
