name: Deploy App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_USE_MSI: "true"
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
  IMAGE_NAME: nextjsbasicapp
  DOCKER_PASSWORD: dckr_pat_eu2ESFDNKYDfUGzafg8Ff3KxULY
  DOCKER_USERNAME: nvonron

jobs:
  build:
    name: Build and Deploy Application
    runs-on: self-hosted
    steps:
      - name: Checkout Repository nextjsbasicapp
        uses: actions/checkout@v4
        with:
          repository: navonron/nextjsbasicapp
          token: ${{ secrets.CHART_REPO_TOKEN }}
          path: nextjsbasicapp

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Log in to Docker Hub
        run: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: navonron/MS-APP
          token: ${{ secrets.CHART_REPO_TOKEN }}
          path: MS-APP

      - name: Set up AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get service nextjsbasicapp-service

#      # Install dependencies and check for vulnerabilities
#      - name: Install Dependencies and Audit
#        working-directory: app/nextjsapp
#        run: |
#          npm install
#          npm audit --production
#
#      # Build the application
#      - name: Build Application
#        working-directory: app/nextjsapp
#        run: npm run build
#
#      # Lint and Test
#      - name: Lint Code
#        working-directory: app/nextjsapp
#        run: npm run lint
#      - name: Run Tests
#        working-directory: app/nextjsapp
#        run: npm test
#
#  containerize:
#    name: Containerize and Push
#    needs: build
#    runs-on: self-hosted
#    steps:
#      # Checkout code
#      - name: Checkout Code
#        uses: actions/checkout@v4
#
#      # Log in to Container Registry
#      - name: Log in to ACR
#        run: az acr login --name ${{ secrets.ACR_NAME }}
#
#      # Build and push the Docker image
#      - name: Build and Push Docker Image
#        run: |
#          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/nextjsapp:${{ github.sha }} .
#          docker push ${{ secrets.ACR_NAME }}.azurecr.io/nextjsapp:${{ github.sha }}
#
#  deploy:
#    name: Deploy to AKS
#    needs: containerize
#    runs-on: self-hosted
#    steps:
#      # Checkout code
#      - name: Checkout Code
#        uses: actions/checkout@v4
#
#      # Configure kubectl
#      - name: Set up AKS
#        run: |
#          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}
#
#      # Deploy to AKS
#      - name: Deploy to AKS
#        run: |
#          kubectl apply -f k8s/deployment.yaml
#          kubectl apply -f k8s/service.yaml
#
#      # Verify Deployment
#      - name: Verify Deployment
#        run: kubectl get pods