name: Deploy Azure Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  ARM_USE_MSI: "true"
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./env/dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init 

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          export exitcode=0
          terraform plan -no-color -var-file="terraform.tfvars" -out main.tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo "Error: Terraform plan failed"
            exit 1
          else
            echo "Terraform plan was successful"
            exit 0
          fi

      - name: Terraform Apply
        run: terraform apply -auto-approve "./main.tfplan"






